extends: existence
message: "If you expect users to copy and run the command, specify one command per code block."
link: https://docs.docker.com/contribute/style/formatting/#best-practice-for-commands
level: warning
scope: raw
#check for console code fence followed by at least two lines with $ or #
raw:
  - '\`\`\`console\n'      # start at ```console
  - '[^(\$|#)]*'           # 0 or more characters without $ or #
  - '.*(\$|#).*\n'         # 1 line with $ or #
  - '[^(\$|#)]*'           #  0 or more characters without $ or #
  - '.*(\$|#).*\n'         # 1 line with $ or #
  - '((?!\`\`\`)(.|\n))*'  # 0 or characters without ```
  - '\`\`\`'               # stop ```

