name: build docker image when PR is opened

on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        uses: docker/bake-action@v2
        with:
          targets: release

  validate:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        uses: docker/bake-action@v2
        with:
          targets: release
      -
        name: Check for broken links
        uses: chabad360/htmlproofer@master
        with:
          directory: ./_site
          # for available options, refer to:
          # - https://github.com/gjtorikian/html-proofer
          # - https://github.com/gjtorikian/html-proofer/blob/main/bin/htmlproofer
          arguments: --disable-external --internal-domains="docs.docker.com,docs-stage.docker.com,localhost:4000" --file-ignore="/^./_site/engine/api/.*$/,./_site/registry/configuration/index.html" --url-ignore="/^/docker-hub/api/latest/.*$/,/^/engine/api/v.+/#.*$/,/^/glossary/.*$/"

      # Disabled netlify-deploy due to flakey 502 http errors
      # - name: copy static files
      #   if: github.event.pull_request.head.repo.fork == false
      #   run: docker run -v ${PWD}:/output documentation:latest cp -r /usr/share/nginx/html /output/_site
      # - uses: ./.github/actions/netlify-deploy
      #   if: github.event.pull_request.head.repo.fork == false
      #   with:
      #     directory: _site
      #     netlify_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     netlify_account_slug: ${{ secrets.NETLIFY_ACCOUNT_SLUG }}
      #     site_name: "${{ github.repository }}/${{ github.head_ref }}"
